let Hotel_List = [
  {
    Title: "Holiday Inn",
    Description: "I have rarely come across a hotel which has made an uttappam and a paratha at the same property and both dishes took me back to the best authentic regional flavours. Kudos to the chefs & team behind this. Also, glad to interact with the guest relations manager while checking in to enjoy a conversation and feel more comfortable in the property, I made my first visit to.",
    Image: "https://digital.ihg.com/is/image/ihg/holiday-inn-new-delhi-3492356108-4x3?wid=750&fit=constrain",
    Price: 18050,
    Location: "New Delhi Int | Airport",
    Country: "India",
  },
  {
    Title: "Crowne Plaza",
    Description: "I guess the title of this review says everything. Crowne Plaza Mayur Vihar has impressed me in every aspect. The front desk people are so warm, they brighten my mood the moment I arrive. Big thanks to Shreya, Devendra, Mahim, Ankit, Shaurya, Pooja, Akash, Oindrila and all the other wonderful people manning the front.",
    Image: "https://digital.ihg.com/is/image/ihg/crowne-plaza-new-delhi-8706054076-2x1?wid=720&fit=constrain",
    Price: 8075,
    Location: "New Delhi Mayur Vihar Noida",
    Country: "India",
  },
  {
    Title: "Trident Nariman Point, hotel in Mumbai",
    Description: "The 5-star Trident Nariman Point is located in Mumbai, overlooking the beautiful Arabian Sea from Marine Drive.",
    Image: "https://cf.bstatic.com/xdata/images/hotel/square600/32810813.webp?k=325fd3b94b42fb8056ab577a3c8342f94540532d4bd8d677017ecac14507399c&o=",
    Price: 24075,
    Location: "Nariman Point, Mumbai",
    Country: "India",
  },
  {
    Title: "The Taj Mahal Tower, Mumbai, hotel in Mumbai",
    Description: "Built in 1973, the iconic The Taj Mahal Tower Mumbai stands majestically across from the Gateway of India, overlooking the Arabian Sea.",
    Image: "https://cf.bstatic.com/xdata/images/hotel/square600/31204963.webp?k=f27ed7e8803d086d2e1e0a8cb3d2dc5950cbf7fed59adb02bc8db1354c2c1323&o=",
    Price: 14000,
    Location: "Apollo Bunder, Mumbai",
    Country: "India",
  },
  {
    Title: "Hilton Garden Inn Bengaluru Embassy Manyata Business Park",
    Description: "Set in Bangalore, 8 km from Commercial Street, Hilton Garden Inn Bengaluru Embassy Manyata Business Park offers accommodation with an outdoor swimming pool, free private parking, a terrace and a restaurant. Conveniently located in the Nagavara district, this hotel features a bar, as well as a sauna. The accommodation provides a 24-hour front desk, airport transfers, room service and free WiFi throughout the property.",
    Image: "https://cf.bstatic.com/xdata/images/hotel/max1280x900/498578544.jpg?k=4c4a20261ad65e6eda5393ba022032ef45734b4e7d8e894e6346a93e9c6617bf&o=&hp=1",
    Price: 10067,
    Location: "Nagavara, Bangalore",
    Country: "India",
  },
  {
    Title: "Radisson Hotel Varanasi",
    Description: "Offering a fitness centre and an outdoor swimming pool, Radisson Hotel Varanasi offers 3 dining options and a bar along with a poolside barbeque. Free Wi-Fi is available throughout the property. Radisson Hotel is located 3 km from local Bus Station and Varanasi Cantonment Railway Station. Nearby attractions include Sarnath Buddhist Place, Main Ghats at the mighty Ganges and Kashi Vishwanath Temple which are at 6 km. The Tulsi Manas Temple is 8 km away while the Lal Bahadur Shastri Babatpur International and Domestic Airport is 22 km.",
    Image: "https://cf.bstatic.com/xdata/images/hotel/max1280x900/26729576.jpg?k=f766d1385ad6d419ebcb8fbfd2d95090faecb36941c58dfd90fc3e639917e669&o=&hp=1",
    Price: 6375,
    Location: "Varanasi Cantt, Varanasi",
    Country: "India",
  },
  {
    Title: "Ramada Plaza by Wyndham JHV Varanasi",
    Description: "Located in Varanasi City, Ramada Plaza by Wyndham JHV Varanasi offers 5 dining options and an outdoor pool. It also boasts a spa, gym and a tennis court. Its spacious rooms feature lawn, pool, or Varuna River views.",
    Image: "https://cf.bstatic.com/xdata/images/hotel/max1280x900/268854033.jpg?k=e84cc83031614cabcaa75cebf871ffeeecab726591b30789ad88aa55f448d77f&o=&hp=1",
    Price: 7500,
    Location: "Varanasi Cantt, Varanasi",
    Country: "India",
  },
  {
    Title: "The Singing Tree",
    Description: "Located in Old Goa, 1.3 km from Vagator Beach, The Singing Tree provides accommodation with a garden, free private parking, a restaurant and a bar. This 3-star hotel offers room service, a 24-hour front desk and free WiFi. The hotel features an indoor pool and luggage storage space.",
    Image: "https://cf.bstatic.com/xdata/images/hotel/square600/511763885.webp?k=5a26fbea7e6be27854d6efbd35407bde8b614551b1f8617f63ed45796692b130&o=",
    Price: 5000,
    Location: "Old Goa",
    Country: "India",
  },
  {
    Title: "Ibis Hyderabad Hitec City - An Accor Brand",
    Description: "Ibis Hyderabad Hitech City is located in Hitec City. Free WiFi access is available throughout the property. Every room is equipped with a flat-screen satellite TV and a tea/coffee maker. The rooms have a seating area where you can relax. Rooms come with a private bathroom. For your comfort, you will find free toiletries and a hair dryer.",
    Image: "https://cf.bstatic.com/xdata/images/hotel/max1280x900/69153252.jpg?k=251edfb4032e59b0d21a222fe9786ff4fc3db0f941dffda29512fc448eb9a7a2&o=&hp=1",
    Price: 6200,
    Location: "HITEC City, Hyderabad",
    Country: "India",
  },
  {
    Title: "Radisson Blu Plaza Hotel Hyderabad Banjara Hills",
    Description: "Get the celebrity treatment with world-class service at Radisson Blu Plaza Hotel Hyderabad Banjara Hills. Just 1 km from GVK One, Hyderabad’s largest shopping mall, the 5-star Radisson Blu Plaza Hotel boasts 3 dining options and an outdoor swimming pool. Guests enjoy free Wi-Fi and free parking.",
    Image: "https://cf.bstatic.com/xdata/images/hotel/square600/329245845.webp?k=ed65a57eb2bf78d5145e1689c00dbe013bde54094df5f4ac3231d765fb3d1881&o=",
    Price: 8250,
    Location: "Hyderabad",
    Country: "India",
  },
  {
    Title: "Hyatt Centric Chandigarh",
    Description: "Located in Chandigarh’s Sector 17 and overlooking Zakir Rose Garden, Hyatt Centric Sector17 Chandigarh features a well-appointed spa and 3 dining options. It offers free WiFi, free parking and rooms with a flat-screen TV. Elegant rooms feature stylish modern interiors. Each is equipped with a personal safe, minibar and an attached bathroom with a shower.",
    Image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/501519356.jpg?k=6162825cc75a38b8e19b23ce1e2a96f2a0c88db09a3ba0cc26613bce5364a37c&o=&hp=1",
    Price: 9100,
    Location: "Chandigarh",
    Country: "India",
  },
  {
    Title: "Park Central",
    Description: "Park Central Hotel offers the convenience of being steps from Central Park. For exercise enthusiasts, the property offers 24-hour onsite fitness centre.",
    Image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/19082406.jpg?k=17006a71f8de2f8523d0450cb03cf3a25a2582270de885fc3c76dbfcdb51a240&o=",
    Price: 12000,
    Location: "New York",
    Country: "USA",
  }
];

module.exports = { data: Hotel_List };
